### PR TITLE
Fixes name clobbering in ec2-pod-role

### PR DESCRIPTION
**Pull request by kotfic**
In some circumstances the `name` variable is being overwritten with
the name of the playbook.  This means if multiple individuals are
launching pods with the same playbook it is not possible to distinguish
between the two.  Changing `name` to `cluster_name` prevents
this from happening.

@opadron PTAL

### CODE REVIEW

**Comment by opadron** [comment]
Do you mean that the name of a particular play is being used instead of the name provided when using the role?

Can you post an example playbook that runs into this issue?

**Comment by kotfic** [comment]
this is in `default.yml`

``` yaml
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    cluster_state: running
    cluster_region: us-west-2
    instance_type: t2.medium
    ec2_pod_spec:
      key: "{{ aws_keyname }}"
      name: "{{ cluster_id }}"
      rules:

        - proto: tcp # ssh
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

        - proto: all
          group_name: ec2_pod_default

      hosts:
        head:
          type: "{{ instance_type }}"

        data:
          type: "{{ instance_type }}"
          count: "{{ instance_count }}"
  roles:
    - role: ec2-pod
      default_ssh_key: "{{ ec2_pod_spec.key }}"
      name: "{{ cluster_id }}"
      # passed in from deployment script
      state: "{{ cluster_state }}"
      region: "{{ cluster_region }}"
      default_image: ami-e0f7e081
      rules: "{{ ec2_pod_spec.rules }}"
      hosts: "{{ ec2_pod_spec.hosts }}"
```

I kept getting 'name'  equal to 'default'  instead of the cluster_id.  Changing 'name'  to 'cluster_name'  in the ec2_pod role resolved the issue.

**Comment by opadron** [comment]
Are you getting a pod name that is literally `== "default"`?  Because the default as defined in the role should be `"pod"`.  I want to be sure this naming issue is indeed with the role, and not something else.

**Comment by kotfic** [comment]
Yes name is equal to `default` - which is why I think there is some kind of conflict in ansible with using 'name'

**Comment by opadron** [comment]
So far, I've not been able to reproduce with a simplified role and playbook.  What version of Ansible are you using, and where is the `{{ cluster_id }}` value coming from?  I don't see it defined in the playbook?

**Comment by kotfic** [comment]
cluster_id is being passed through the pythonic API as an extra var - it shoudl be like calling the playbook with the `-e` flag

**Comment by kotfic** [comment]
Sorry,  I am using ansible 1.9.4

**Comment by opadron** [comment]
Even when reusing @kotfic's [script](https://github.com/Kitware/cumulus/blob/ansible-refactor/cumulus/ansible/tasks/cluster.py) from cumulus, I have not been successful in reproducing the issue this PR is meant to address.

Since I can't reproduce the issue, and considering that most of the gobig codebase will need to be totally revamped to take advantage of ansible 2.0, anyway, I'm closing this PR without merge.

**Pull request closed without merging**
