### PR TITLE
fix ec2 provisioning

### PR DESCRIPTION
**Pull request by opadron**
First in what will become a series of change sets for migrating to Ansible 2.0.  Note that this PR seeks to merge the changes to a new branch: `ansible2`.  All changes specific to Ansible 2.0 should be merged into this branch until all roles/filters/modules have been migrated.

Changes detailed below:
- remove variable prefix feature from the aws-credentials role
  - The aws-credentials role now unconditionally sets aws_access_key_id and
    aws_secret_key.
- add git_cache module
  - to eventually replace the git-cache role
- update the aws-credentials and ec2-pod2 roles to use correct syntax for
  long string literals that do not preserve the trailing newline.

### CODE REVIEW

**Comment by opadron** [comment]
@kitware/gobig

**Comment by kotfic** [comment]
@opadron Addition of `instance_profile_name` to the role would be a great help for my work. This gives launched instances permissions on AWS based on an IAM role (e.g. for downloading/uploading to S3).

**Comment by opadron** [comment]
@kotfic I think we should make that feature another issue/pr.  Do the changes LGTY, IAM features notwithstanding?

**Comment by kotfic** [comment]
yep,  LGTM

On Mon, Apr 4, 2016 at 12:07 PM, Omar Padron notifications@github.com
wrote:

> @kotfic https://github.com/kotfic I think we should make that feature
> another issue/pr. Do the changes LGTY, IAM features notwithstanding?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/Kitware/gobig/pull/57#issuecomment-205369800

## 

Christopher Kotfila
R&D Engineer
Kitware Inc.
http://www.kitware.com/company/team/kotfila.html

**Comment by opadron** [comment]
resolved via #65

**Pull request closed without merging**
