### PR TITLE
MongoDB Rework

### PR DESCRIPTION
**Pull request by opadron**
More and more, I'm finding that simple updates to GoBig seldom turn out so simple.  This PR, originally meant as just a fix to #42, is a testament to this observation.

Once I switched the mongodb roles to being proper roles (as opposed to dumb wrappers around apt), I knew I needed to add configuration options to meet the inevitably varied needs of those who might want to use them.  The more I dug into the docs, though, the more apparent the need to cover use cases requiring replica sets and sharding became.

This code is _indeed_ a WIP, but it should help others to see what I'm going for.

### CODE REVIEW

**Comment by opadron** [comment]
@kotfic PTAL.  I don't have access to any resources that I can test this on.  Could I send you some playbooks to try on AWS?  Hopefully, this shouldn't require much more work to handle the simple case of just installing a stand alone MongoDB.

**Comment by kotfic** [comment]
@opadron do you have a motivating use-case for the sharding and replication set work? I can deploy to some virtual machines locally to test these out,  but they are features of mongo that I am not particularly familiar with,  I'll need a pretty straightforward use-case and test playbook.

**Comment by opadron** [comment]
For now, I think the current example playbook should be enough to reproduce a standalone install of mongo (with a newer version than what's in ubuntu's repos).

``` YAML
  - hosts: mongodb
    roles:
      - role: mongodb
        state: started
```

**Comment by opadron** [comment]
@Kitware/gobig Ready for review.

**Comment by kotfic** [comment]
@opadron looks like there are some string mangling issues (there is a \n in the download url)?

```
TASK: [mongodb-install | mongodb | pkg | download] **************************** 
<127.0.0.1> REMOTE_MODULE command creates=/opt/mongodb/mongodb-3.2.0.tar.gz curl -o "/opt/mongodb/mongodb-3.2.0.tar.gz" "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64- 3.2.0.tgz"
failed: [minerva] => {"changed": true, "cmd": ["curl", "-o", "/opt/mongodb/mongodb-3.2.0.tar.gz", "https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-\n3.2.0.tgz"], "delta": "0:00:00.012142", "end": "2016-01-18 15:34:49.200065", "rc": 3, "start": "2016-01-18 15:34:49.187923", "warnings": ["Consider using get_url module rather than running curl"]}
stderr: curl: (3) Illegal characters found in URL

FATAL: all hosts have already failed -- aborting

```

**Comment by opadron** [comment]
Fixed.  Apparently, when you use syntax like the one below for a string block:

``` YAML
my_string: >
    long string that I didn't expect to have a newline at the end
```

you get a newline tacked onto the end.

Someday, I will understand YAML's syntax.  I can dream.

**Comment by kotfic** [comment]
ansible script is now completing but mongod is throwing an error.  From `/var/log/mongodb.log`:

```
Error parsing YAML config file: yaml-cpp: error at line 4, column 4: end of map not found
try '/opt/mongodb/3.2.0/bin/mongod --help' for more information
```

**Comment by opadron** [comment]
@kotfic PTAL

**Comment by kotfic** [comment]
@opadron  LGTM!

**Pull request merged**
